	\context ChordNames
		\chords {
		\set Score.markFormatter = #format-mark-box-numbers

		% intro
		\skip 1*3

		% resucito...
		\mark \default
		\skip 1*16

		% la muerte...
		\mark \default
		\skip 1*8

		% resucito...
		\mark \default
		\skip 1*16

		% gracias...
		\mark \default
		\skip 1*8

		% resucito...
		\mark \default
		\skip 1*16

		% alegria...
		\mark \default
		\skip 1*8

		% aleluya...
		\mark \default
		\skip 1*16
		}
