\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		e1:m e1:m e4:m r2.

		% resucito...
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7

		% la muerte...
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7

		% resucito...
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7

		% gracias...
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7

		% resucito...
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7

		% alegria...
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7

		% resucito...
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7
		e1:m e1:m d1 d1 c1 c1 b1:7 b1:7

		% finale
		e1:m
	}
